name: Run Integration Tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the backend repository
      - name: Checkout Backend Repository
        uses: actions/checkout@v3
        with:
          repository: gklsenthil/e-commerce
          token: ${{ secrets.GITHUB_TOKEN }}
          path: backend

      - name: Pull Latest Changes
        working-directory: ./backend
        run: git pull origin main

      # Step 2: Install dependencies
      - name: Install Backend Dependencies
        working-directory: ./backend
        run: mvn install

      # Step 3: Run test cases
      - name: Run Test Cases
        working-directory: ./backend
        run: mvn test

      # Step 4: Publish results
      - name: Publish Results
        if: always() # Always runs, regardless of success or failure
        run: |
          if [ ${{ job.status }} == 'success' ]; then
            echo "All tests passed successfully!"
          else
            echo "Tests failed. Build cannot proceed."
          fi
